Biometric/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = "biometric"

urlpatterns = [
    path('check/', views.check, name="check"),
    path('username/verify', views.verify_username, name="verify_username"),
    path('report/<int:duration>/<str:username>/', views.report, name="report"),
    path('emails/', views.send_mails, name="emails"),
]

Monitor/urls.py
from django.contrib import admin
from django.urls import path, include

from Biometric import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bio/', include('Biometric.urls', namespace="bio")),
    path('', views.check, name="check"),
]

Biometric/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Employee(models.Model):

    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=50, null=True)
    gender = models.CharField(max_length=8, choices=GENDER, null=True)

    def __unicode__(self):
        return self.user.username

    def __str__(self):
        return self.user.username


# Hooking the following methods to the Django defined User model
@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **_):
    if created:
        Employee.objects.create(user=instance)
    try:
        instance.employee.save()
    except Exception:
        pass


class Log(models.Model):
    LOG_TYPE_MAP = {
        1: "Check in",
        2: "Check out",
    }

    LOG_TYPE = tuple(zip(LOG_TYPE_MAP.keys(), LOG_TYPE_MAP.values()))

    employee = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now())
    nature = models.IntegerField(choices=LOG_TYPE, null=False)

    def __unicode__(self):
        return f"{self.LOG_TYPE_MAP.get(self.nature)} by {self.employee.username} at {self.date.strftime('%c')}"

    def __str__(self):
        return f"{self.LOG_TYPE_MAP.get(self.nature)} by {self.employee.username} at {self.date.strftime('%c')}"

Biometric/views.py
from datetime import timedelta, datetime

from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives, get_connection
from django.db.models import QuerySet
from django.http import JsonResponse, Http404
from django.shortcuts import render
from django.template.loader import get_template

from Biometric.models import Log, Employee


def check(request):
    if request.user.is_authenticated:
        username = request.POST.get("username")
        if username is not None:
            user = User.objects.filter(username=username)
            if user.exists():
                employee = user[0]
                logs = Log.objects.filter(employee=employee).order_by("date")
                log = Log(employee=employee)
                if logs.exists() and logs[logs.count() - 1].nature == 1:
                    log.nature = 2
                    state = "out"
                else:
                    log.nature = 1
                    state = "in"
                log.save()
                return render(request, "result.html", {"user": employee, "state": state, "current": request.user})

    return render(request, "check.html", {"current": request.user})


def format_delta(delta: timedelta):
    format_ = ""
    if delta.days > 0:
        format_ += "{} days ".format(delta.days)
    hours = int(delta.seconds) // 3600
    if hours > 0:
        format_ += "{} hr{} ".format(hours, "" if hours == 1 else "s")
    mins = (int(delta.seconds) - hours * 3600) // 60
    format_ += "{} min{} ".format(mins, "" if mins == 1 else "s")

    return format_


def prepare_email(request, username):
    user = User.objects.filter(username=username)
    prepare_emails()
    if user.exists():
        user = user[0]
        today = datetime.now()
        logs = user.log_set.filter(date__month=today.month, date__year=today.year,
                                   date__day=today.day).order_by("-date")
        return render(request, "email.html", {"user": user, "period": "Today", "logs": logs, "net": calc_net(logs)})


def prepare_emails():
    employees = Employee.objects.all()
    emails = set()
    today = datetime.now()
    for employee in employees:
        html_template = get_template("email.html")
        text_template = get_template("email.text")
        logs = employee.user.log_set.filter(date__month=today.month, date__year=today.year,
                                            date__day=today.day).order_by("-date")
        context = {"user": employee.user, "period": "Today", "logs": logs, "net": calc_net(logs)}
        html_email = html_template.render(context)
        text_email = text_template.render(context)
        email = EmailMultiAlternatives(subject="Biometric attendance report",
                                       to=[employee.user.email], body=text_email)
        email.attach_alternative(html_email, "text/html")
        emails.add(email)

    return emails


def send_mails(request):
    connection = get_connection()

    messages = prepare_emails()
    connection.send_messages(messages)
    return render(request, "emails_sent.html", {"count": len(messages)})


def calc_net(queryset: QuerySet):
    total = timedelta()
    queryset = queryset.order_by("-date")
    for i in range(queryset.count()):
        if queryset[i].nature == 1 and i > 0:
            total += queryset[i - 1].date - queryset[i].date

    return format_delta(total)


def report(request, duration, username):
    periods = ("All time", "This month", "This week", "Today")
    if request.user.is_authenticated:
        user = User.objects.filter(username=username)
        if user.exists():
            user = user[0]
            today = datetime.now()
            if duration == 0:
                # All time
                logs = user.log_set.order_by("-date")
            elif duration == 1:
                # This month
                logs = user.log_set.filter(date__month=today.month, date__year=today.year).order_by("-date")
            elif duration == 2:
                # This week
                logs = user.log_set.filter(date__year=today.year).order_by("-date")
                # This method is very inefficient but creating a custom SQL lookup would be daunting
                filtered = []
                for log in logs:
                    week = log.date.isocalendar()[1]
                    if week == today.isocalendar()[1]:
                        filtered.append(log.id)
                # Calc_net requires queryset
                logs = user.log_set.filter(pk__in=filtered)
            elif duration == 3:
                # Today
                logs = user.log_set.filter(date__month=today.month, date__year=today.year,
                                           date__day=today.day).order_by("-date")
            else:
                raise Http404("Period not found")
            return render(request, "report.html", {"logs": logs, "user": user, "net": calc_net(logs),
                                                   "duration_name": periods[duration], "periods": periods,
                                                   "duration": duration, "current": request.user})

    raise Http404("User not found")


def verify_username(request):
    username = request.POST.get("username")
    if username is not None:
        user = User.objects.filter(username=username)
        if user.exists():
            return JsonResponse({"verified": 1})

    return JsonResponse({"verified": 0})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Biometric Monitor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    {% block styles %}{% endblock %}
    <link rel="shortcut icon" type="image/png" href={% static "images/fingerprint.png" %}>
    <link rel="stylesheet" href={% static "css/main.css" %}>
</head>
<body>
    <div class="main-heading" style="justify-content: space-between">
        <img class="logo-img" src={% static "images/fingerprint.png" %}>
        <p class="heading-text">Biometric Monitor</p>
    <div style="display: inline-flex">
        <a class="button-2 right" href={% url "bio:check" %}>Check in</a>
        {% if current.is_staff %}
        <a class="button-2 right" href="/admin/">Admin panel</a>
        <a class="button-2 right" href={% url "biometric:emails" %}>Send mails</a>
        {% endif %}
    </div>
    </div>
    {% block content %}{% endblock %}
</body>
<script src={% static "js/jquery-3.3.1.min.js" %}></script>
<script src={% static "js/jquery.dajax.js" %}></script>
{% block scripts %}{% endblock %}
</html>

templates/check.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<form class="content" id="checkin-form" method="post" action={% url "bio:check" %}>
    {% csrf_token %}
    <label>Username</label>
    <input name="username" id="username" type="text">
    <p id="message" class="error"></p>
    <input type="submit" id="submit" style="display: none">
    <button class="button" id="checkin" type="button" onclick="preCheck()">Check in / out</button>
</form>
{% endblock %}
{% block scripts %}
    <script>
        let csrf = document.getElementsByName("csrfmiddlewaretoken")[0].value;
        function verify() {
            return new Promise(((resolve, reject) => {
                $.ajax({
                    type: "POST",
                    url: "/bio/username/verify",
                    data: {"username": $("#username").val() , "csrfmiddlewaretoken": csrf},
                    success: function (response){
                        if(response.verified === 1){
                            console.log("yeah");
                            resolve();
                        }else{
                            reject();
                        }
                    },
                    error: function () {
                        reject();
                    }
                })
            }));
        }

        function preCheck(){
            if(!$("#username").val()){
                $("#message").text("username cannot be empty");
                return;
            }
            $("#checkin").text("Verifying...");
            verify().then(()=>{
                $("#message").text("");
                $("#submit ").trigger("click");
            }, ()=>{
                $("#checkin").text("Check in/ out");
                $("#message").text("user not found");
            });
        }
    </script>
{% endblock %}

templates/email.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Biometric Monitor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="shortcut icon" type="image/png" href={% static "images/fingerprint.png" %}>
    <link rel="stylesheet" href={% static "css/main.css" %}>
    <style>
        body{
            margin: 0;
            padding: 2px;
            font-family: Calibri, sans-serif;
        }
        .main-heading{
            background: #f7f7f7;
            width: 100%;
            height: 60px;
            padding: 10px 0 10px 0;
            display: flex;
        }

        .heading-text{
            color: #1c5739;
            font-size: 40px;
            display: inline-flex;
            margin: 0;
            height: 100%;
        }

        .logo-img{
            width: 50px;
            height: 50px;
            display: inline-flex;
        }

        input{
            border: solid 1px #303030;
            border-radius: 15px;
            color: #1c5739;
            outline: transparent;
            display: block;
            width: 100%;
            height: 30px;
            margin: 15px auto;
            padding: 4px;
        }

        .button{
            background: #1c5739;
            color: #f7f7f7;
            border: none;
            height: 40px;
            margin: 30px auto;
            border-radius: 25px;
            cursor: pointer;
            padding: 5px 15px 5px 15px;
            outline: transparent;
        }

        .button-2, .button-2:visited{
            border: solid 1px #1c5739;
            border-radius: 18px;
            height: 20px;
            display: inline-block;
            margin: 5px 10px 10px 5px;
            padding: 5px;
            color: #1c5739;
            transition: linear 0.5s;
            font-size: 15px;
            text-decoration: none;
            cursor: pointer;
        }

        .selected{
            background: #1c5739;
            color: #f7f7f7!important;
        }

        .right{
            float: right;
        }

        .button-2:hover{
            background: #1c5739;
            color: #f7f7f7;
        }

        .error{
            font-size: 12px;
            color: orangered;
            margin: 10px 0 10px 0;
        }

        .text{
            color: #303030;
            font-size: 18px;
        }

        .text-subtitle{
            font-size: 27px;
            text-align: left;
            width: 100%;
            margin: 20px auto;
            padding: 10px;
            border-bottom: solid 1px #dddddd;
            color: #808080;
        }

        .text-medium{
            font-size: 20px;
            color: #1c5739;
            padding: 10px;
            margin: 0 auto;
        }

        .content{
            width: 98%;
            max-width: 300px;
            margin: 150px auto;
            font-size: 15px;
        }

        tr, th{
            height: 35px;
            font-size: 18px;
            color: #303030;
        }

        th{
            color: #1c5739;
        }

        .highlighted{
            background: #f7f7f7;
        }

        td{
            height: 30px;
            vertical-align: middle;
        }
        th{
            text-align: left;
        }
    </style>
</head>
<body>
    <div class="main-heading" style="justify-content: space-between">
        <p class="heading-text">Biometric Monitor</p>
    </div>
    <div class="text-subtitle">
        <p class="text-medium" style="display: inline-block"> Attendance report for {{ user.username }}</p>
        <a class="button-2 right selected">{{ period }}</a>
    </div>
    <p class="text-medium">You have worked for: {{ net }}</p>
    <table id="logs" style="width: 98%; max-width: 700px; margin: 0 auto">
    {% if logs|length > 0 %}
        <tr>
            <th>Nature</th>
            <th>Date</th>
            <th>Time</th>
        </tr>
    {% endif %}
        {% for log in logs %}
            <tr class="{% cycle 'highlighted' '' %}">
                <td>{% if log.nature == 1 %}Check in{% else %}Check out{% endif %}</td>
                <td>{{ log.date|date}}</td>
                <td>{{ log.date|time}}</td>
            </tr>
            {% empty %}
            <div class="heading-text" style="text-align: center; display: block">No logs yet</div>
        {% endfor %}
    </table>
</body>
<script src={% static "js/jquery-3.3.1.min.js" %}></script>
<script src={% static "js/jquery.dajax.js" %}></script>
</html>

templates/emails_sent.html
{% load static %}
{% block styles %}
    <style>
        #result .centered{
            display: block;
            margin: 30px auto;
            text-align: center;
        }
    </style>
{% endblock %}
{% block content %}
    <div id="result" style="display: block; margin-top: 100px">
        <img alt="check" class="centered" width="200" height="200" style="border-radius: 100px" src={% static "images/check.png" %}>
        <div class="heading-text centered" style="color: #33b984"> Emails sent successfully to {{ count }} employees</div>
    </div>
{% endblock %}

templates/report.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    <style>
        #logs tr th{
            width: 30%;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="text-subtitle">
        <p class="text-medium" style="display: inline-block"> Attendance report for {{ user.username }}</p>
        {% for period in periods %}
            <a class="button-2 right {% if duration_name == period %}selected{% else %}{% endif %}" href={% url "bio:report" forloop.counter0 user.username%}>{{ period }}</a>
        {% endfor %}
    </div>
    <p class="text-medium">{{ user.username }} has worked for: {{ net }}</p>
    <table id="logs" style="width: 98%; max-width: 700px; margin: 0 auto">
    {% if logs|length > 0 %}
        <tr>
            <th>Nature</th>
            <th>Date</th>
            <th>Time</th>
        </tr>
    {% endif %}
        {% for log in logs %}
            <tr class="{% cycle 'highlighted' '' %}">
                <td>{% if log.nature == 1 %}Check in{% else %}Check out{% endif %}</td>
                <td>{{ log.date|date}}</td>
                <td>{{ log.date|time}}</td>
            </tr>
            {% empty %}
            <div class="heading-text" style="text-align: center; display: block">No logs yet</div>
        {% endfor %}
    </table>
{% endblock %}

templates/result.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
    <style>
        #result .centered{
            display: block;
            margin: 30px auto;
            text-align: center;
        }
    </style>
{% endblock %}
{% block content %}
    <div id="result" style="display: block; margin-top: 100px">
        <img class="centered" width="200" height="200" style="border-radius: 100px" src={% static "images/person.png" %}>
        <p class="centered text">{{ user.username }}</p>
        <div class="heading-text centered" style="color: #33b984"> Checked {{ state }} successfully</div>
        <a href={% url "bio:report" 0 user.username%}><button class="button centered"> View User report</button></a>
    </div>
{% endblock %}